### ISSUE TITLE
Let's see some more custom themes!

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#30]

**Comment by s10wen** [comment]
Boom! https://github.com/mauricecruz/zero-base-themes/blob/master/themes/tomorrow-night.less
Boom! https://github.com/mauricecruz/zero-base-themes/blob/master/themes/tomorrow-night-bright.less
Boom! https://github.com/mauricecruz/zero-base-themes/blob/master/themes/dark-soda-monokai.less

Keep them coming :dancer:

**Comment by mauricecruz** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers:
