### ISSUE TITLE
Canary drop down styling

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#39]
Stable: 40.0.2214.94:
![screen shot 2015-02-05 at 10 53 30](https://cloud.githubusercontent.com/assets/1136114/6059059/4debce4e-ad25-11e4-8a0a-c3d69ff95b03.png)

Canary: 42.0.2295.0:
![screen shot 2015-02-05 at 10 53 17](https://cloud.githubusercontent.com/assets/1136114/6059062/571c5b14-ad25-11e4-96b2-f8a403160aed.png)

**Comment by mauricecruz** [comment]
i've tried to fix it.. but I can't override their shadow dom property. I can't quite figure it out. I can override the `background-color` and `text-decoration`, but not the `color`. But I think they all have the same specificity level.

https://pbs.twimg.com/tweet_video/B8lUQ_OIUAAop8g.mp4

**Comment by s10wen** [comment]
@mauricecruz tried the `cmd+shift+c` trick but still can't get at this! Maybe @paulirish can help us out?

**Comment by mauricecruz** [comment]
Yea the node disappears when you lose devtools focus. You can put a breakpoint in devtool's devtools here:

![image](https://cloud.githubusercontent.com/assets/1640686/6067854/8b0d27ee-ad45-11e4-928b-b55eb727042c.png)

That'll pause the script before it removes the node so you can inspect it.

**Comment by mauricecruz** [comment]
![image](https://cloud.githubusercontent.com/assets/1640686/6074655/4b1a0e12-ad91-11e4-86aa-73ed6099ada9.png)

Found a way to fix it. There's a handful of new selectors specific to shadow dom. Apparently you can target 'light DOM' nodes inside shadow DOM.

**Comment by s10wen** [comment]
@mauricecruz skills!!
