### ISSUE TITLE
Canary > Settings > Devices

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#40]
![screen shot 2015-02-08 at 12 30 00](https://cloud.githubusercontent.com/assets/1136114/6096530/41d9ef62-af8e-11e4-88d9-dbfea2f1a330.png)

**Comment by mauricecruz** [comment]
![image](https://cloud.githubusercontent.com/assets/1640686/6097587/c4a8caa0-af91-11e4-96c9-260e8746604b.png)
