### ISSUE TITLE
fix call stack notification style

### ISSUE THREAD

**Issue by mauricecruz** [mauricecruz/zero-base-themes#46]
![image](https://cloud.githubusercontent.com/assets/1640686/6110093/7314e40a-b04d-11e4-97bf-6d69fe83d1d7.png)

**Comment by s10wen** [comment]
How can I get the 'show' to show please dude? All I get is this:
![screen shot 2015-02-10 at 10 43 02](https://cloud.githubusercontent.com/assets/1136114/6125769/af485866-b111-11e4-93e8-d15bb86dcca3.png)

**Comment by mauricecruz** [comment]
Hah i actually forgot. I think it requires you to add a blackboxed script.

**Comment by mauricecruz** [comment]
@s10wen i managed to fix this. Will push it up later.

**Comment by s10wen** [comment]
Swish :swimmer:
