### ISSUE TITLE
Elements style column buttons

### ISSUE THREAD

**Issue by wkerswell** [mauricecruz/zero-base-themes#56]
Is there a way to change these buttons to make them more visible? 
![Elements style column](http://imgur.com/9UjnFCW.png)

I am using the s10wen-monokai theme and have the most current changes checked out and compiled. 
Let me know if I am missing something.

Many thanks.

**Comment by s10wen** [comment]
hey @wkerswell yeah, I'll try and look at this today for you.

**Comment by s10wen** [comment]
Improved it the best I could for now, it's an image sprite so a bit trickier.

![screen shot 2015-06-03 at 10 22 32](https://cloud.githubusercontent.com/assets/1136114/7956866/002c7448-09db-11e5-9efc-1892300fa161.png)

**Comment by s10wen** [comment]
Sorted :+1: 

![screen shot 2015-06-03 at 10 34 59](https://cloud.githubusercontent.com/assets/1136114/7957017/398a7cac-09dc-11e5-8e9d-ae0b8ed37d57.png)

**Comment by wkerswell** [comment]
Hero! <3

**Comment by mauricecruz** [comment]
:clap:
