### ISSUE TITLE
Styles > css background highlights 

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#57]
Started noticing these recently, @mauricecruz are you getting similar?

![screen shot 2015-06-25 at 15 25 40](https://cloud.githubusercontent.com/assets/1136114/8356660/8d17bf78-1b4e-11e5-91da-443b4158fd89.png)

**Comment by mauricecruz** [comment]
What version is this?



- Maurice

**Comment by s10wen** [comment]
Version 43.0.2357.130 (64-bit)

**Comment by mauricecruz** [comment]
yup.. getting the same thing. Hmm wonder if I caused a regression. I know I handled it before and the version didn't bump up. 

Must've happened whilst doing some cleanup and updates for Canary. Will patch this week.

**Comment by s10wen** [comment]
Ace, I'll watch out for it, I might have some time week to tidy a few things up as well.

**Comment by mauricecruz** [comment]
Think this is fixed now. Please confirm.

**Comment by s10wen** [comment]
Swish :dancer: 
![screen shot 2015-08-15 at 14 13 21](https://cloud.githubusercontent.com/assets/1136114/9288957/b9b5cf08-4357-11e5-8b27-8c3cb31827fe.png)
