### ISSUE TITLE
Not working in latest stable Chrome 44.0.2403.89

### ISSUE THREAD

**Issue by BillClinton** [mauricecruz/zero-base-themes#58]
Developers tool theme "DevTools Theme: Zero Dark Matrix" is no longer working after Chrome update to 44.0.2403.89 on Windows 8.  Comments in the Reviews and Support sections of the Chrome webstore plug-in page indicate others are having the same issue.

(awesome/plugin/theme btw)

**Comment by mauricecruz** [comment]
Thanks! 

Experiments settings reset in `44.0.2403.89`. 
Open developer tools settings &#9654; Experiments &#9654; [&#10004;] Allow custom UI themes to enable theme again.

**Comment by BillClinton** [comment]
that did it, thanks!
