### ISSUE TITLE
README.md: Update extension instructions

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#61]
Reminder for me to updated the instructions re loading in via the Chrome Extension vs point to local repo

**Comment by KLVTZ** [comment]
:+1:

**Comment by s10wen** [comment]
Think this was related to `Chrome > Preferences... > Extensions > DevTools Theme: Zero Dark Matrix = Enabled (also enable Allow incognito below if you wish).` that's now in the `README.md`.

@mauricecruz please can you confirm.
