### ISSUE TITLE
packaged themes give errors

### ISSUE THREAD

**Issue by leshow** [mauricecruz/zero-base-themes#63]
I've got a fresh clone of this repo. When I change config.less from
```
// Select Theme
@theme : "zero-dark-matrix";
```
to one of the other themes included, such as:

```
@theme: "tomorrow-night";
```
I get build errors:
```
Running "less:generate" (less) task
>> NameError: variable @glyph-background is undefined in less/_panel-sources.less on line 136, column 20:
>> 135 .panel.elements .sidebar-pane .sidebar-pane-toolbar .pane-title-button.add {
>> 136 	background-color: @glyph-background !important;
>> 137 }
```

I've tried 3 or 4 different themes included in the project and they all generate errors except for the default matrix theme.

Is the readme out of date? What am I missing?

**Comment by mauricecruz** [comment]
The `glyph-background` variable was missing from a few of the themes. I updated the repo to remove the variable because the implementation has changed and it's no longer used. Pull down the latest update and all the themes should work. @s10wen
