### ISSUE TITLE
Update styles for closing tags

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#64]
![screen shot 2015-10-21 at 09 21 44](https://cloud.githubusercontent.com/assets/1136114/10631315/30cbb13c-77d5-11e5-8b75-9250fa825b26.png)

Looks like there's some extra styles to consider for closing tags in the Elements tab.

**Comment by wkerswell** [comment]
Yeah I noticed this too.

**Comment by s10wen** [comment]
![screen shot 2015-10-21 at 11 11 59](https://cloud.githubusercontent.com/assets/1136114/10633737/96675564-77e4-11e5-853a-1d58432bc500.png)

This should be fixed now :dancer:

**Comment by mauricecruz** [comment]
sorry for the delay all. Have a sizeable commit on my local that is addresss both stable/canary rendering issues. Will push out shortly.
