### ISSUE TITLE
Element tag arrows not pointing down

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#65]
![screen shot 2015-10-22 at 10 46 33](https://cloud.githubusercontent.com/assets/1136114/10662136/3b4a9148-78aa-11e5-9a59-d0baa98c3f22.png)

The arrow should point down when the tag is open.

**Comment by mauricecruz** [comment]
@s10wen what version? I see down arrows on v46 stable and v48 Canary

**Comment by s10wen** [comment]
Version 46.0.2490.71 (64-bit)
OS X 10.10.5 (14F27)

**Comment by mauricecruz** [comment]
Let me spin up a virtual and check it out.

**Comment by s10wen** [comment]
Seem like an issue with `false` settings in `config.less`

**Comment by s10wen** [comment]
Yeah it is when `.show-animations( true );` is set as true it works again, personally I prefer without animations, but currently prevents the down arrow from kicking in.

**Comment by mauricecruz** [comment]
OSX Yosemite.

![image](https://cloud.githubusercontent.com/assets/1640686/10668838/141234a8-78ac-11e5-9a93-39dd4c6de929.png)

**Comment by mauricecruz** [comment]
Ahhh ok I can fix that. Let me look into it.

**Comment by s10wen** [comment]
.show-animations( true );

**Comment by mauricecruz** [comment]
fixed pushed up. try it out and let me know!

**Comment by s10wen** [comment]
HAPPY(*・▽・)／＼(･▽･*）HAPPY
