### ISSUE TITLE
Update dev tools split widget resizer to be wider

### ISSUE THREAD

**Issue by s10wen** [mauricecruz/zero-base-themes#67]
I'm looking at doing something along these lines:
http://recordit.co/rAEteTah7f

1) Any idea how to force the `width: 20px` to stay active on resize?

2) Where would this code best live? I'm thinking this might be best as a `true/false` as not everyone might want this behaviour.

**Comment by mauricecruz** [comment]
I'll give it a try and see what options are out there when I get a free moment. Been busy - just started a new gig.

I think it makes more sense to have it as theme property e.g. `dock-border-width` and just set the default to whatever size it is now in the theme template and boost yours up to your liking.

**Comment by s10wen** [comment]
Congrats on the new gig! Nice one, sounds like a plan.

**Comment by mauricecruz** [comment]
Ever get around to figuring this one out?

**Comment by s10wen** [comment]
Nope, sorry dude. Less time to work on this these days.

**Comment by mauricecruz** [comment]
@s10wen gonna close this one out if you don't mind.

**Comment by s10wen** [comment]
@mauricecruz sure thing, hope you're well :)
