### ISSUE TITLE
Style suggestion box on console

### ISSUE THREAD

**Issue by summers173** [mauricecruz/zero-base-themes#71]
Is there a way to style the background of the suggestion box on console, is useful for auto complete and with the white background is difficult to read on black themes,

Best regards

P.D. Thanks for save my eyes everyday

**Comment by mauricecruz** [comment]
You're welcome!

Can you tell me which Chrome version you're using? The suggestion box normally is styled.

![](http://take.ms/3QPTb)

**Comment by summers173** [comment]
Hello Maurice,

My chrome Version 50.0.2661.102 m, and bellow is how I see the suggestion box, I change some colors on the less file, but even with the original 'zero-dark-matrix' I get the same un styled suggestion box.

Best regards, and thanks a lot for your time

![imagen 002](https://cloud.githubusercontent.com/assets/5115255/15219230/8dfb5486-1828-11e6-8522-165e55c5825d.jpg)

**Comment by mauricecruz** [comment]
Ahh, you know what I haven't pushed up my latest code in a few weeks because I created some variables that will break the other themes. I'll get my latest changes up on the repo soon.

**Comment by summers173** [comment]
Thanks pal, looking forward to get those changes, regards

**Comment by mauricecruz** [comment]
Latest push up on the repo. There's a new less partial called `var-catch` which has all the new variables that might not exist on other theme sheets. It'll paint whatever you don't have declared in red.

**Comment by summers173** [comment]
Thanks a lot, looks amazing, dark in all screens. I going to open another issue, if you can help me.

![imagen 002](https://cloud.githubusercontent.com/assets/5115255/15229454/c0d307e0-1856-11e6-81d0-c08179bca7d4.jpg)
