### ISSUE TITLE
Style 'React Developer Tools' extension

### ISSUE THREAD

**Issue by summers173** [mauricecruz/zero-base-themes#72]
Hello again Maurice, now I have to learn ReactJs for a project, I installed the 'React Developer Tools' extension, which you can find here

https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?utm_source=chrome-app-launcher-info-dialog

With the knowledge that you have about the console, I want to ask you if there is a way to style this white borders

![imagen 002](https://cloud.githubusercontent.com/assets/5115255/15229557/29a27620-1857-11e6-98a6-2042f1499df4.jpg)

which ends here

![imagen 003](https://cloud.githubusercontent.com/assets/5115255/15229563/2f50ba8c-1857-11e6-93f6-6cbde99f335b.jpg)

With that I´ll have a full dark theme in the whole console.

Once again, thanks for all your work.

**Comment by mauricecruz** [comment]
I took a look at the code they used to write the app and it looks like they're inlining all the styles and there aren't any class hooks to bind to the elements. So unfortunately, theming won't work at all.

Someone repackaged their app and styled it with a different dark theme though - https://github.com/dqisme/react-devtool-with-tomorrow-theme. 

The only catch is that this fork won't be updated in sync with the actual react devtools.

**Comment by summers173** [comment]
Understood, thanks a lot Maurice, keep the great work.
