### ISSUE TITLE
Devtool Extension Panel

### ISSUE THREAD

**Issue by WORMSS** [mauricecruz/zero-base-themes#73]
Is it possible for a Chrome DevTool Extension to pick up this theme in a custom panel?

https://developer.chrome.com/extensions/devtools_panels

My Panel just shows generic black text (I am not colouring them myself). But it does pick up the dark background. But that is it.
- Colin

**Comment by mauricecruz** [comment]
Hey sorry I missed this. If a custom panel doesn't set a background, I believe the background of the custom panel is 'transparent' by default. So whatever background devtools has, will show through the custom pane.

**Comment by WORMSS** [comment]
The background is not the problem but more the text colour. It may have a transparent background, but the default text colour of a custom panel is black. On the dark theme, if the dark background shows through, then everything becomes impossible to read.

So I as just wondering how can I set the text colour to pickup the zero-base-themes colour? Or better yet, what ever theme is currently active's colour.

- Colin.

**Comment by mauricecruz** [comment]
Just made an update to set the `sidebar-pane` default text to the global text color of whatever theme is loaded.

I'm not 100% sure this is gonna work, but I injected some random strings into the panel and it looked like it was working. Let me know how it turns out.
