### ISSUE TITLE
Rendered Fonts are illegible

### ISSUE THREAD

**Issue by theetrain** [mauricecruz/zero-base-themes#74]
Great theme! I noticed this while inspecting computed styles:

![image](https://cloud.githubusercontent.com/assets/12798751/16173785/dba522ba-357a-11e6-98bf-06cc72571452.png)

Right now it's only possible to read the rendered fonts if I highlight it:

![image](https://cloud.githubusercontent.com/assets/12798751/16173792/fc020ff0-357a-11e6-872d-194073265ac2.png)

**Comment by mauricecruz** [comment]
awesome! thanks for reporting this. I'll patch it up.



- Maurice

**Comment by mauricecruz** [comment]
Fixed in 2.1.5 on webstore.
