### ISSUE TITLE
Network tab

### ISSUE THREAD

**Issue by stoivo** [mauricecruz/zero-base-themes#76]
First of, I love the theme❤️💖  

Chrome version: Version 56.0.2924.87 (64-bit)
Network tab, 
![screen shot 2017-03-15 at 14 59 09](https://cloud.githubusercontent.com/assets/3492040/23951915/0459990e-0990-11e7-8db7-32e8105b8510.png)

It looks like the theme only covers every second.

**Comment by stoivo** [comment]
It seems to be working in Canary so probably nothing to think of.

**Comment by mauricecruz** [comment]
From what I remember, the panel is styled via SVG. I haven't figured out a way to modify styles in there. Not sure if I can.

But, if you enable Chrome's native dark theme, it'll paint the lines dark.
![image](https://cloud.githubusercontent.com/assets/1640686/23956180/67e5afee-0972-11e7-8b03-31a47715aedf.png)

![image](https://cloud.githubusercontent.com/assets/1640686/23956222/7ed3cbaa-0972-11e7-83e5-3b1dcd21ba15.png)

**Comment by stoivo** [comment]
Thanks,
