### ISSUE TITLE
Change color of @media on editor styles

### ISSUE THREAD

**Issue by joniEAHH** [mauricecruz/zero-base-themes#80]
Hi,

I'm trying to create a theme with material colors but I can't find the variable to insert the color of media queries on styles editor

![image](https://user-images.githubusercontent.com/6386032/52640545-a3eefd00-2ece-11e9-9620-b34eeeb37c85.png)

Any tip about it?

**Comment by joniEAHH** [comment]
Ok. Selecting theme dark on developer tools settings fixed the color of media queries.

**Comment by joniEAHH** [comment]
Ok. Selecting theme dark on developer tools settings fixed the color of media queries.

**Comment by mauricecruz** [comment]
Hey sorry I didn't get to this sooner. The method that injects the custom stylesheets is a bit faulty. Doesn't really work on dynamic dom elements. 

Using the native dark theme is the best fallback right now.
